baseurl: "https://xuanqi.life"
languageCode: "cn-zh"
title: "Xuanqi"
theme: "hugo-xmin"
googleAnalytics: "G-WS87Q8XEJL"
disqusShortname: "xuanqi"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: 博客 Blog
      url: ""
      weight: 1
    - name: 介绍 About
      url: "about/"
      weight: 2
#    - name: 分类 Categories
#      url: "categories/"
#      weight: 3
#    - name: 标签 Tags
#      url: "tags/"
#      weight: 4
#    - name: 订阅 Subscribe
#      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Xuanqi](https://xuanqi.life/) 2022 -- {Year} | [Douban](https://www.douban.com/people/xuanqi1122/)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
